### ISSUE TITLE
Build error under VS 2019 environment

### ISSUE THREAD

**Issue by fkclai** [0dteam/Phishing-Reporter#1]
Hi,

The following error was reported when followed the instruction and build the project.

"Unable to find manifest signing certificate in the certificate store."

I tried to unclick the "Sign the ClickOnce manifests", but it clicked again automatically and shown the same error.
https://i.stack.imgur.com/FIHjg.png

May I have your help?

thanks,

**Comment by fkclai** [comment]
To resolve this problem, you can delete the following code at the file "PhishingReporter.csproj", before you start the project


  <PropertyGroup>
    <SignManifests>true</SignManifests>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestKeyFile>PhishingReporter_TemporaryKey.pfx</ManifestKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestCertificateThumbprint>49F4622D1A7A5798A0337CEE03366CECC8D37E0C</ManifestCertificateThumbprint>
  </PropertyGroup>1

**Comment by derhelge** [comment]
You can also add a tempory Certificate by yourself inside the project-settings.
