### ISSUE TITLE
Build as EXE

### ISSUE THREAD

**Issue by y0d4a** [0dteam/Phishing-Reporter#10]
Hi,

I tried to make a exe as installation for this plugin, but without luck, always got vsto file which is not friendly for mass deployment ...
How i can build .exe from it?
or is there option to make silent install of this vsto, so i can easily make mass distribution ?

thank you

**Comment by 0dteam** [comment]
Hello,

Read "Before you start" section and follow "How-to Guide" in this link:
https://www.0d.ae/report-phishing-plugin-for-outlook

Let me know how it goes.

**Comment by y0d4a** [comment]
hm, first i try with visual 2019 and 2022, and nothing, i just downloaded 2017 and tried again, and it is the same...
What i think is the problem:
![image](https://user-images.githubusercontent.com/3115997/174566303-ba9907df-0405-430b-af03-7f12b8ee4561.png)
but not sure how to rsolve it, what ever i try, it is fail, he do not create msi binary...

**Comment by y0d4a** [comment]
ok, something was stuck, after reloading project, all pass fine! 
thank you for support and this installation! it was only missing part with gophish :)

**Comment by 0dteam** [comment]
I am glad to hear you have resolved the issue.
Enjoy the plugin :)
