### ISSUE TITLE
Office 2016

### ISSUE THREAD

**Issue by mirfaelltkeinnameein** [0dteam/Phishing-Reporter#11]
Hi,
you wrote an important and great tool. It works on stations with Office 2019 (as you wrote), but unfortunately not on stations with Office 2016. Can you give me an advice to resolve this problem? Many thanks in advance.

**Comment by 0dteam** [comment]
Hello.
I have tested this plugin in Outlook 2016 as well; and it is working fine.
Make sure you follow the [How To Guide ](https://github.com/0dteam/Phishing-Reporter#how-to-guide)

If you have a specific issue, please share screenshots/logs that can help me investigate further.

**Comment by mirfaelltkeinnameein** [comment]
Hi,I am very sorry, but now I have another issue.If I build the project (32-bit version) I get an error that there is no manifest.dll and no PhishingReporter.vsto. The files are not available, but how can I get it?Kind regards,Susanne --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 14.08.23, 18:50 schrieb 0d Team ***@***.***>:

   
  Hello. I have tested this plugin in Outlook 2016 as well; and it is working fine. Make sure you follow the How To Guide  
  If you have a specific issue, please share screenshots/logs that can help me investigate further.

**Comment by 0dteam** [comment]
> Hi,I am very sorry, but now I have another issue.If I build the project (32-bit version) I get an error that there is no manifest.dll and no PhishingReporter.vsto. The files are not available, but how can I get it?Kind regards,Susanne --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 14.08.23, 18:50 schrieb 0d Team ***@***.***>: Hello. I have tested this plugin in Outlook 2016 as well; and it is working fine. Make sure you follow the How To Guide If you have a specific issue, please share screenshots/logs that can help me investigate further. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Try this:
- First, set the solution configuration to "Release"
- Build the solution. This will generate the missing file you mentioned.
- Last, right-click "Installer" and select "Build"

Let me know if this works for you.

**Comment by mirfaelltkeinnameein** [comment]
Hi, that does not work.
Maybe I cannot build the solution because of using an 64-bit Windows System?
Kind regards.

Gesendet von Mail für Windows

Von: 0d Team
Gesendet: Donnerstag, 21. September 2023 17:23
An: 0dteam/Phishing-Reporter
Cc: mirfaelltkeinnameein; Author
Betreff: Re: [0dteam/Phishing-Reporter] Office 2016 (Issue #11)

Hi,I am very sorry, but now I have another issue.If I build the project (32-bit version) I get an error that there is no manifest.dll and no PhishingReporter.vsto. The files are not available, but how can I get it?Kind regards,Susanne --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 14.08.23, 18:50 schrieb 0d Team @.>: Hello. I have tested this plugin in Outlook 2016 as well; and it is working fine. Make sure you follow the How To Guide If you have a specific issue, please share screenshots/logs that can help me investigate further. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.>
Try this:
• First, set the solution configuration to "Release"
• Build the solution. This will generate the missing file you mentioned.
• Last, right-click "Installer" and select "Build"
Let me know if this works for you.

**Comment by motsamaimokheseng** [comment]
Hi. 

I'm having an issue when building the solution due to signing required.

**Comment by csabaoszkar85** [comment]
> Hi.
> 
> I'm having an issue when building the solution due to signing required.


The solution for that would be in [this ](https://stackoverflow.com/questions/11957295/unable-to-find-manifest-signing-certificate-in-the-certificate-store-even-wh)thread. This did the job for me.

**Comment by csabaoszkar85** [comment]
@0dteam respect for this tool, a hell of a job made here!
I have one tiny little issue that still doesn't work, otherwise it works perfectly, as described in the guide. For some particular reason when I send a campaign phishing email from GoPhish and report it with the tool, it doesn't deliver the correct message (that this was a simulation), and also it doesn't reflect in the GoPhish admin dashboard as reported.
Any suggestions, where should I start investigating the cause?
Many thanks!

**Comment by 0dteam** [comment]
> @0dteam respect for this tool, a hell of a job made here! I have one tiny little issue that still doesn't work, otherwise it works perfectly, as described in the guide. For some particular reason when I send a campaign phishing email from GoPhish and report it with the tool, it doesn't deliver the correct message (that this was a simulation), and also it doesn't reflect in the GoPhish admin dashboard as reported. Any suggestions, where should I start investigating the cause? Many thanks!

Thanks for the kind words.
Regarding the issue you have, please specify which GoPhish version you are using.
I haven't tested the plugin for 3 years. I think it might not be compatible with GoPhish latest versions but I will need to check first.

**Comment by 0dteam** [comment]
> [!NOTE]
**Added** new commit
**Added** _Integration with GoPhish_ guide to the official [article](https://www.0d.ae/report-phishing-plugin-for-outlook)
**Updated** README.md

**Comment by csabaoszkar85** [comment]
Many thanks you for the update @0dteam.
I have adjusted it accordingly and I can confirm that this works as a charm now!
Great job! 🙏
