### ISSUE TITLE
No count of reported, simulated phishing emails

### ISSUE THREAD

**Issue by mirfaelltkeinnameein** [0dteam/Phishing-Reporter#13]
**Describe the bug**
If you receive a real phishing-email, you can report it via the button and it works fine with both versions (32- and 64-bit), but if you want to send a simulated phishing-mail it works the same, but in the gophish dashboard there is no counting at "email reported". With the 64-bit version all is working fine.
The image shows the results of 2 simulated phishing emails that were sent, one with the 32-bit version and one with the 64-bit version. The counter was increased by one for the message with the 64-bit version.
![image](https://github.com/0dteam/Phishing-Reporter/assets/126671209/90195f2c-c2ea-4471-8505-1ee600ef2359)
 
**Expected behavior**
If somebody report a simulated phishing mail, the counter in the gophish dashboard should be incremented.

**Screenshots**
![image](https://github.com/0dteam/Phishing-Reporter/assets/126671209/d41a06fc-dd8f-407c-b78c-6d11d193a73b)

**Desktop (please complete the following information):**
 - OS: Windows, 32-bit

**Comment by 0dteam** [comment]
Could you specify your GoPhish version so I can replicate the issue and troubleshoot?

**Comment by 0dteam** [comment]
> [!NOTE]
**Added** new commit
**Added** _Integration with GoPhish_ guide to the official [article](https://www.0d.ae/report-phishing-plugin-for-outlook)
**Updated** README.md

**Comment by mirfaelltkeinnameein** [comment]
Hi,the version is 0.12.1Thanks a lot.Kind regards --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 20.12.23, 20:01 schrieb 0d Team ***@***.***>:

   
  Could you specify your GoPhish version so I can replicate the issue and troubleshoot?

**Comment by 0dteam** [comment]
This should be resolved now after the last commit.
