### ISSUE TITLE
can we export PAB manifest for Microsoft products  for this reporter ?

### ISSUE THREAD

**Issue by cyberx-company** [0dteam/Phishing-Reporter#17]
can we export PAB manifest for Microsoft products  for this reporter ?

**Comment by cyberx-company** [comment]
@0dteam ?

**Comment by 0dteam** [comment]
@cyberx-company 
No. This is a VSTO add-in.
On the other side, I have started developing a web add-in version (with Manifest). I will tag you if I release it.

**Comment by cyberx-company** [comment]
@0dteam 
yes plz , thank you.
