### ISSUE TITLE
Outlook disable plugin - Slow Start Add-in

### ISSUE THREAD

**Issue by sebaeee** [0dteam/Phishing-Reporter#2]
Sometimes, Outlook disable the plugin due slow start.

![image](https://user-images.githubusercontent.com/33755980/99075837-e9a39280-2598-11eb-99ed-04470461b454.png)

**Comment by 0dteam** [comment]
You can always enable the add-in from "File" >"Manage COM Add-ins" > "Always enable this add-in".

**Comment by sebaeee** [comment]
I can´t select an Always enable, and we need make this centralized in a corp, registry, gpo o something like this

![image](https://user-images.githubusercontent.com/33755980/99082175-90406100-25a2-11eb-9b2b-40fccf952b35.png)

**Comment by 0dteam** [comment]
You can follow the steps in one of these guides:
https://www.techhit.com/how-to/prevent-outlook-from-disabling-add-in/
https://docs.microsoft.com/en-us/office/vba/outlook/concepts/getting-started/support-for-keeping-add-ins-enabled
