### ISSUE TITLE
Header info as attachment

### ISSUE THREAD

**Issue by sebaeee** [0dteam/Phishing-Reporter#3]
Hi, this isn´t an issue. How can I send the information in bode as txt attachment with the eml (2 attachment in total)
I see this code, I need to put this on a second txt attachment.

                            // Prepare the email body
                            reportEmail.Body = GetCurrentUserInfos();
                            reportEmail.Body += "\n";
                            reportEmail.Body += GetBasicInfo(mailItem);
                            reportEmail.Body += "\n";
                            reportEmail.Body += GetURLsAndAttachmentsInfo(mailItem);
                            reportEmail.Body += "\n";
                            reportEmail.Body += "---------- Headers ----------";
                            reportEmail.Body += "\n" + reportedItemHeaders;
                            reportEmail.Body += "\n";
                            reportEmail.Body += GetPluginDetails() + "\n\n";

                            reportEmail.Save();
                            //reportEmail.Display(); // Helps in debugginng
                            reportEmail.Send(); // Automatically send the email

**Comment by sebaeee** [comment]
I can try to put all reportEmail.Body on a txt file and then attach to the report email, but I don´t know if this is the best way, or create something on memory.

**Comment by 0dteam** [comment]
You can find few examples on how to acheive this:
https://stackoverflow.com/questions/5336239/attach-a-file-from-memorystream-to-a-mailmessage-in-c-sharp
https://stackoverflow.com/questions/38099292/writing-list-of-strings-into-text-file-adding-as-attachment-to-the-mail-using-c

**Comment by sebaeee** [comment]
Thanks
